#!/usr/bin/env python3
import subprocess
import sys


def usage():
    print("Usage: ./initall [-f] start end")


av = list(sys.argv)
if len(av) < 2:
    usage()
    exit(0)

force = False
if "-f" in av:
    force = True
    av.remove("-f")

low, high = None, None
try:
    low, high = int(av[1]), int(av[2])
except:
    usage()
    exit(0)

if high - low > 10:
    print(
        "Do not recommend initing too many, edit the program if you still want to do it"
    )
    exit(0)

# run init for all letters
for i in range(low, high + 1):
    subprocess.run("./init Day" + str(i) + (" -f" if force else ""), shell=True)
